### ISSUE TITLE
RCS and usernames

### ISSUE THREAD

**Issue by alexcrichton** [aidanhs/simpleinfra#3]
Right now the user on rust-central-station is just the bland "ubuntu" whereas I'm normally "acrichton", "acrichto", or "alex" locally. The script for restarting RCS starts out uses `$USER` to ssh, but perhaps we could rely on `~/.ssh/config` to configure that? (that's what I've done in the past)

**Comment by aidanhs** [comment]
Ah I don't really use `.ssh/config` so I didn't think of it. It's a far better idea though, done and documented.
