### ISSUE TITLE
RCS and rsync

### ISSUE THREAD

**Issue by alexcrichton** [aidanhs/simpleinfra#4]
I saw that the restart script for now starts out with an `rsync`, and it also has `--delete`! I don't currently store the secrets locally, so maybe we could skip that for now and just persist the secrets on the target machine? (until we sort out #2)

**Comment by aidanhs** [comment]
Oops! That's very bad, you told me this and I documented the change I intended to make (removing the rsync)...but didn't actually remove it! Done now.
