### ISSUE TITLE
RCS and shells?

### ISSUE THREAD

**Issue by alexcrichton** [aidanhs/simpleinfra#5]
I tried using the script this morning but it failed for a few reasons:

* Executed as `./restart-rcs.sh` it says "./restart-rcs.sh: 1: set: Illegal option -o pipefail", but I fixed this with `bash ./restart-rcs.sh`
* Otherwise the `ssh` command doesn't actually do anything. I didn't get an error message or anything but I figured that it was something odd with the string syntax. I'm terrible with multiline shell strings!

Did you use bash for this? Another shell? Don't mind installing anything, just curious! (and the script should prolly start w/ `#!/bin/$shell`)

**Comment by aidanhs** [comment]
Ah yes, I do use bash so I can do those three 'strict shell mode' things.

I think that multiline script should be fine - if it exited silently, I suspect `/opt/rcs/data` does not exist, or is not a directory? It needs to contain the secrets. I've now added xtrace so you can see commands executing, as well as a better error message if that directory doesn't exist.

**Comment by alexcrichton** [comment]
Ok yeah that must have been it! I think I was fooled with cached ssh connections because it was exiting so quickly... In any case looks good now (xtrace is definitely helpful)
